server.port=8083
spring.application.name=user-management-gateway
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always
authentication.service.url=${AUTHENTICATION_SERVICE_URL:http://localhost:8084}
user.profile.service.url=${USER_PROFILE_SERVICE_URL:http://localhost:8085}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%X{serviceName}] [%thread] %logger{36} - %msg%n
logging.level.com.jobseekercopilot=${APP_LOG_LEVEL:INFO}
